version: '3.7'

volumes:
  postgres:
  mysql:

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=test_messaging
      - POSTGRES_USER=user_messaging
      - POSTGRES_PASSWORD=e5YGE3cQ2ysqHesT
    volumes:
      - postgres:/var/lib/postgresql
      - postgres:/var/log/postgresql
      - ./pg_init.sql:/docker-entrypoint-initdb.d/10-init.sql
    ports:
      - "54320:5432"

  redis:
    image: redis:7.0.0
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6378:6379'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    volumes:
      - /var/lib/rabbitmq
    command: [
      "bash", "-c",
      "rabbitmq-plugins enable rabbitmq_consistent_hash_exchange; docker-entrypoint.sh rabbitmq-server"
    ]
    ports:
      - 5672:5672
      - 15672:15672

  localstack:
    container_name: localstack
    image: localstack/localstack-light:0.14.0
    ports:
      - 4566:4566
      - 4571:4571
    environment:
      HOSTNAME_EXTERNAL: localstack
      SERVICES: "sns,sqs,s3"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: test

  crdb:
    image: cockroachdb/cockroach:v21.2.7
    ports:
      - "26257:26257"
      - "8090:8080"
    command: start-single-node --insecure

  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    command: --sql_mode=NO_ENGINE_SUBSTITUTION
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test_vehicleservice
      MYSQL_USER: test
      MYSQL_PASSWORD: test
